// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

// During build time (prisma generate), Railway environment variables are not available
// Use a fallback value that won't cause the build to fail
// The actual DATABASE_URL will be used at runtime from environment variables
// We use a dummy URL for build time - prisma generate only needs to read the schema
const DATABASE_URL = 'postgresql://dummy:password@localhost:5432/db';

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: DATABASE_URL,
  },
});

