// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { DATABASE_URL } from "./config/env.config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
      url: DATABASE_URL
  },
});
